// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fycucpnfvrocwtjxtjsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Y3VjcG5mdnJvY3d0anh0anNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzAxNTMsImV4cCI6MjA2ODA0NjE1M30.iDdseF5QMGHUNur_iEg9fXNsmytLzWGvkmIfFZUiIIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});